development:
  adapter: mysql2
  database: starbox_development
  username: root
  password: 
  host: localhost

test:
  adapter: mysql2
  database: starbox_test
  username: root
  password: 
  host: localhost

# production:
#   adapter: mysql
#   database: pool_ride_production
#   username: root
#   password:
#   host: localhost
